var books = [
  {
    price: "Free",
    name: "Release That Witch ปล่อยแม่มดคนนั้นซะ ภาค 1",
    type: "สร้างเมือง",
    images: "r1.jpg",
    folder: "e/1/",
    chapters: 88,
    status: "Complete",
    by: "เอ่อร์มู่ (二目)",
    // banner: 'new',
    main: true,
  },
  {
    price: "Free",
    name: "Release That Witch ปล่อยแม่มดคนนั้นซะ ภาค 2",
    type: "สร้างเมือง",
    images: "r1.jpg",
    folder: "e/2/",
    chapters: 385,
    status: "Complete",
    by: "เอ่อร์มู่ (二目)",
    // banner: 'new',
    main: true,
  },
  {
    price: "Free",
    name: "ฉันนี่แหละคือซูเปอร์สตาร์ ภาค 1",
    type: "แฟนตาซี",
    images: "d1.jpg",
    folder: "d/1/",
    chapters: 98,
    status: "Complete",
    by: "ฉางอวี้ (尝谕)",
    // banner: 'new',
    main: true,
  },
  {
    price: "Free",
    name: "ฉันนี่แหละคือซูเปอร์สตาร์ ภาค 2",
    type: "แฟนตาซี",
    images: "d1.jpg",
    folder: "d/2/",
    chapters: 101,
    status: "Complete",
    by: "ฉางอวี้ (尝谕)",
    // banner: 'new',
    main: true,
  },
  {
    price: "Free",
    name: "ฉันนี่แหละคือซูเปอร์สตาร์ ภาค 3",
    type: "แฟนตาซี",
    images: "d1.jpg",
    folder: "d/3/",
    chapters: 100,
    status: "Complete",
    by: "ฉางอวี้ (尝谕)",
    // banner: 'new',
    main: true,
  },
  {
    price: "Free",
    name: "ฉันนี่แหละคือซูเปอร์สตาร์ ภาค 4",
    type: "แฟนตาซี",
    images: "d1.jpg",
    folder: "d/4/",
    chapters: 100,
    status: "Complete",
    by: "ฉางอวี้ (尝谕)",
    // banner: 'new',
    main: true,
  },
  {
    price: "Free",
    name: "ฉันนี่แหละคือซูเปอร์สตาร์ ภาค 5",
    type: "แฟนตาซี",
    images: "d1.jpg",
    folder: "d/5/",
    chapters: 100,
    status: "Complete",
    by: "ฉางอวี้ (尝谕)",
    // banner: 'new',
    main: true,
  },
  {
    price: "Free",
    name: "ฉันนี่แหละคือซูเปอร์สตาร์ ภาค 6",
    type: "แฟนตาซี",
    images: "d1.jpg",
    folder: "d/6/",
    chapters: 100,
    status: "Complete",
    by: "ฉางอวี้ (尝谕)",
    // banner: 'new',
    main: true,
  },
  {
    price: "Free",
    name: "ฉันนี่แหละคือซูเปอร์สตาร์ ภาค 7",
    type: "แฟนตาซี",
    images: "d1.jpg",
    folder: "d/7/",
    chapters: 100,
    status: "Complete",
    by: "ฉางอวี้ (尝谕)",
    // banner: 'new',
    main: true,
  },
  {
    price: "Free",
    name: "ฉันนี่แหละคือซูเปอร์สตาร์ ภาค 8",
    type: "แฟนตาซี",
    images: "d1.jpg",
    folder: "d/8/",
    chapters: 103,
    status: "Complete",
    by: "ฉางอวี้ (尝谕)",
    // banner: 'new',
    main: true,
  },
  {
    price: "Free",
    name: "ฉันนี่แหละคือซูเปอร์สตาร์ ภาค 9",
    type: "แฟนตาซี",
    images: "d1.jpg",
    folder: "d/9/",
    chapters: 97,
    status: "Complete",
    by: "ฉางอวี้ (尝谕)",
    // banner: 'new',
    main: true,
  },
  {
    price: "Free",
    name: "ฉันนี่แหละคือซูเปอร์สตาร์ ภาค 10",
    type: "แฟนตาซี",
    images: "d1.jpg",
    folder: "d/10/",
    chapters: 280,
    status: "On going",
    by: "ฉางอวี้ (尝谕)",
    banner: "new",
    main: true,
  },
  {
    price: "Free",
    name: "ผนึกสวรรค์ สยบมาร สะท้านเทพ ภาค 1 - ปรมาจารย์เอกะเทวะ",
    type: "กำลังภายใน",
    images: "c1.jpg",
    folder: "c/1/",
    chapters: 95,
    status: "Complete",
    by: "เอ่อร์เกิน (耳根)",
    // banner: 'new',
    main: true,
  },
  {
    price: "514 บาท",
    name: "หนึ่งความคิดนิจนิรันดร์ ภาค 1 เขาชื่อป๋ายเสี่ยวฉุน",
    type: "กำลังภายใน",
    images: "x1.jpg",
    chapters: 183,
    folder: "a/1/",
    status: "Complete",
    by: "เอ่อร์เกิน (耳根)",
    main: true,
  },
  {
    price: "496 บาท",
    name: "หนึ่งความคิดนิจนิรันดร์ ภาค 2 ตำนานของเย่จั้ง",
    type: "กำลังภายใน",
    images: "x1.jpg",
    chapters: 143,
    folder: "a/2/",
    status: "Complete",
    by: "เอ่อร์เกิน (耳根)",
    main: true,
  },
  {
    price: "169 บาท",
    name: "หนึ่งความคิดนิจนิรันดร์ ภาค 3 สยบธารลุกผงาด",
    type: "กำลังภายใน",
    images: "x1.jpg",
    chapters: 52,
    folder: "a/3/",
    status: "Complete",
    by: "เอ่อร์เกิน (耳根)",
    main: true,
  },
  {
    price: "648 บาท",
    name: "หนึ่งความคิดนิจนิรันดร์ ภาค 4 ตัวประกันที่แตกต่าง",
    type: "กำลังภายใน",
    images: "x1.jpg",
    chapters: 185,
    folder: "a/4/",
    status: "Complete",
    by: "เอ่อร์เกิน (耳根)",
    main: true,
  },
  {
    price: "1100 บาท",
    name: "หนึ่งความคิดนิจนิรันดร์ ภาค 5 จุดสูงสุดของชีวิต",
    type: "กำลังภายใน",
    images: "x1.jpg",
    chapters: 291,
    folder: "a/5/",
    status: "Complete",
    by: "เอ่อร์เกิน (耳根)",
    main: true,
  },
  {
    price: "900 บาท",
    name: "หนึ่งความคิดนิจนิรันดร์ ภาค 6 คนฟ้าที่แข็งแกร่งที่สุด",
    type: "กำลังภายใน",
    images: "x1.jpg",
    chapters: 189,
    folder: "a/6/",
    status: "Complete",
    by: "เอ่อร์เกิน (耳根)",
    main: true,
  },
  {
    price: "1400 บาท",
    name: "หนึ่งความคิดนิจนิรันดร์ ภาค 7 ดินแดนเซียนนิรันดร์กาล",
    type: "กำลังภายใน",
    images: "x1.jpg",
    chapters: 289,
    folder: "a/7/",
    status: "Complete",
    by: "เอ่อร์เกิน (耳根)",
    main: true,
  },
  {
    price: "Free",
    name: "King of Gods ราชันเทพเจ้า ภาค 1",
    type: "กำลังภายใน",
    images: "x2.jpg",
    folder: "b/1/",
    chapters: 184,
    status: "Complete",
    by: "主宰之王 (Zhu Zai Zhi Wang)",
    main: true,
  },
  {
    price: "108 บาท",
    name: "King of Gods ราชันเทพเจ้า ภาค 2",
    type: "กำลังภายใน",
    images: "x2.jpg",
    folder: "b/2/",
    chapters: 37,
    status: "Complete",
    by: "主宰之王 (Zhu Zai Zhi Wang)",
    main: true,
  },
  {
    price: "774 บาท",
    name: "King of Gods ราชันเทพเจ้า ภาค 3",
    type: "กำลังภายใน",
    images: "x2.jpg",
    chapters: 220,
    folder: "b/3/",
    status: "Complete",
    by: "主宰之王 (Zhu Zai Zhi Wang)",
    main: true,
  },
  {
    price: "410 บาท",
    name: "King of Gods ราชันเทพเจ้า ภาค 4",
    type: "กำลังภายใน",
    images: "x2.jpg",
    chapters: 119,
    folder: "b/4/",
    status: "Complete",
    by: "主宰之王 (Zhu Zai Zhi Wang)",
    main: true,
  },
  {
    price: "712 บาท",
    name: "King of Gods ราชันเทพเจ้า ภาค 5",
    type: "กำลังภายใน",
    images: "x2.jpg",
    folder: "b/5/",
    chapters: 203,
    status: "Complete",
    by: "主宰之王 (Zhu Zai Zhi Wang)",
    main: true,
  },
  {
    price: "XX บาท",
    name: "King of Gods ราชันเทพเจ้า ภาค 6",
    type: "กำลังภายใน",
    images: "x2.jpg",
    folder: "b/6/",
    chapters: 381,
    status: "Complete",
    // banner: 'new',
    by: "主宰之王 (Zhu Zai Zhi Wang)",
    main: true,
  },
  {
    price: "XX บาท",
    name: "King of Gods ราชันเทพเจ้า ภาค 7",
    type: "กำลังภายใน",
    images: "x2.jpg",
    folder: "b/7/",
    chapters: 441,
    status: "Complete",
    banner: "new",
    by: "主宰之王 (Zhu Zai Zhi Wang)",
    main: true,
  },
  {
    price: "Free",
    name: "ท้าลิขิตพลิกโชคชะตา",
    type: "กำลังภายใน",
    images: "f1.jpeg",
    folder: "f/1/",
    chapters: 948,
    status: "On going",
    by: "猫腻 (เมานี่)",
    banner: "new",
    main: true,
  }
];
